<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Oxygen - One Page HTML Template | Themeum</title>
        <link href="customer/css/bootstrap.min.css" rel="stylesheet">
        <link href="customer/css/animate.min.css" rel="stylesheet"> 
        <link href="customer/css/font-awesome.min.css" rel="stylesheet">
        <link href="customer/css/lightbox.css" rel="stylesheet">
        <link href="customer/css/main.css" rel="stylesheet">
        <link id="css-preset" href="customer/css/presets/preset1.css" rel="stylesheet">
        <link href="customer/css/responsive.css" rel="stylesheet">

        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
          <script src="js/respond.min.js"></script>
        <![endif]-->

        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
        <link rel="shortcut icon" href="customer/images/favicon.ico">
    </head><!--/head-->

    <body class="row">

        <!--.preloader-->
        <div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
        <!--/.preloader-->

        <header id="home">
            <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="item active" style="background-image: url(customer/images/slider/1.jpg)">
                        <div class="caption">
                            <h1 class="animated fadeInLeftBig">Welcome to <span>Oxygen</span></h1>
                            <p class="animated fadeInRightBig">Bootstrap - Responsive Design - Retina Ready - Parallax</p>
                            <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Start now</a>
                        </div>
                    </div>
                    <div class="item" style="background-image: url(customer/images/slider/2.jpg)">
                        <div class="caption">
                            <h1 class="animated fadeInLeftBig">Say Hello to <span>Oxygen</span></h1>
                            <p class="animated fadeInRightBig">Bootstrap - Responsive Design - Retina Ready - Parallax</p>
                            <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Start now</a>
                        </div>
                    </div>
                    <div class="item" style="background-image: url(customer/images/slider/3.jpg)">
                        <div class="caption">
                            <h1 class="animated fadeInLeftBig">We are <span>Creative</span></h1>
                            <p class="animated fadeInRightBig">Bootstrap - Responsive Design - Retina Ready - Parallax</p>
                            <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Start now</a>
                        </div>
                    </div>
                </div>
                <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>

                <a id="tohash" href="#services"><i class="fa fa-angle-down"></i></a>

            </div><!--/#home-slider-->
            <div class="main-nav">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.html">
                            <h1><img class="img-responsive" src="customer/images/logo.png" alt="logo"></h1>
                        </a>                    
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">                 
                            <li class="scroll active"><a href="#home">Home</a></li>
                            <li class="scroll"><a href="#services">Service</a></li> 
                            <li class="scroll"><a href="#about-us">About Us</a></li>                     
                            <li class="scroll"><a href="#portfolio">Portfolio</a></li>
                            <li class="scroll"><a href="#team">Team</a></li>
                            <li class="scroll"><a href="#blog">Blog</a></li>
                            <li class="scroll"><a href="#contact">Contact</a></li>       
                        </ul>
                    </div>
                </div>
            </div>
            <!--/#main-nav-->
        </header>
        <script type="text/javascript" src="customer/js/jquery.js"></script>
        <script type="text/javascript" src="customer/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script type="text/javascript" src="customer/js/jquery.inview.min.js"></script>
        <script type="text/javascript" src="customer/js/wow.min.js"></script>
        <script type="text/javascript" src="customer/js/mousescroll.js"></script>
        <script type="text/javascript" src="customer/js/smoothscroll.js"></script>
        <script type="text/javascript" src="customer/js/jquery.countTo.js"></script>
        <script type="text/javascript" src="customer/js/lightbox.min.js"></script>
        <script type="text/javascript" src="customer/js/main.js"></script>

    </body>
</html>